SELECT A.AUTHOR_ID,	
       B.AUTHOR_NAME,	
       A.CATEGORY,	
       SUM(A.PRICE * C.SALES) AS TOTAL_SALES
  FROM BOOK AS A 
  LEFT OUTER JOIN AUTHOR     AS B ON B.AUTHOR_ID = A.AUTHOR_ID
  LEFT OUTER JOIN BOOK_SALES AS C ON C.BOOK_ID = A.BOOK_ID
 WHERE YEAR(C.SALES_DATE) = 2022        # 2022-01인 데이터만 추출
   AND MONTH(C.SALES_DATE) = 1
  GROUP BY A.AUTHOR_ID, A.CATEGORY
  ORDER BY A.AUTHOR_ID, A.CATEGORY DESC