-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, 
       MAX(A.PRICE) * SUM(B.SALES_AMOUNT) AS 'SALES' -- 매출액(판매가 * 판매량)
  FROM PRODUCT AS A 
    RIGHT OUTER JOIN OFFLINE_SALE  AS B ON B.PRODUCT_ID = A.PRODUCT_ID
  GROUP BY A.PRODUCT_CODE
  ORDER BY SALES DESC, A.PRODUCT_CODE ASC