-- 코드를 입력하세요
SELECT A1.FOOD_TYPE, A1.REST_ID, A1.REST_NAME, A1.FAVORITES
  FROM REST_INFO AS A1 
    JOIN (SELECT A.FOOD_TYPE, MAX(B.FAVORITES) AS 'FAVORITES'
            FROM REST_INFO AS A 
                JOIN REST_INFO AS B ON B.REST_ID = A.REST_ID
           GROUP BY A.FOOD_TYPE) AS B1  ON  B1.FOOD_TYPE = A1.FOOD_TYPE 
                                        AND B1.FAVORITES = A1.FAVORITES
  ORDER BY A1.FOOD_TYPE DESC