-- 코드를 입력하세요
SELECT A.REST_ID,
       A.REST_NAME,
       A.FOOD_TYPE,       
       A.FAVORITES,
       A.ADDRESS,
       ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
  FROM REST_INFO AS A
    JOIN REST_REVIEW AS B ON B.REST_ID = A.REST_ID
 WHERE A.ADDRESS like '서울%'
 GROUP BY A.REST_ID
 ORDER BY 6 DESC, A.FAVORITES DESC -- 평균점수를 기준으로 내림차순,즐겨찾기수를 기준으로 내림차순 