-- 코드를 작성해주세요
SELECT A.ROUTE, 
       CONCAT(ROUND(SUM(A.D_BETWEEN_DIST),1), 'km') AS TOTAL_DISTANCE, 
       CONCAT(ROUND(AVG(A.D_BETWEEN_DIST),2), 'km') AS AVERAGE_DISTANCE
  FROM SUBWAY_DISTANCE  AS A 
 GROUP BY ROUTE 
 ORDER BY ROUND(SUM(A.D_BETWEEN_DIST),1) DESC -- 총 누계 거리를 기준으로 내림차순 정렬