-- 2021년에 가입한 사용자 수
SET @Total_Join := (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021);


SELECT YEAR(B.SALES_DATE) AS 'YEAR', 
       MONTH(B.SALES_DATE) AS 'MONTH', 
       COUNT(DISTINCT  B.USER_ID) AS 'PURCHASED_USERS', 
       ROUND(COUNT(DISTINCT  B.USER_ID) / @Total_Join, 1) AS 'PURCHASED_RATIO'
FROM USER_INFO AS A 
     JOIN ONLINE_SALE AS B ON B.USER_ID = A.USER_ID
WHERE YEAR(A.JOINED) = '2021'
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE) ASC