-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
	SELECT ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE, 1 AS 'GENERATION'
	  FROM ECOLI_DATA
	 WHERE PARENT_ID IS NULL     
     UNION ALL
	SELECT B.ID, B.PARENT_ID, B.SIZE_OF_COLONY, B.DIFFERENTIATION_DATE,B.GENOTYPE, A.GENERATION + 1 
	  FROM CTE AS A
	  INNER JOIN ECOLI_DATA AS B ON B.PARENT_ID = A.ID	
)
SELECT COUNT(1) AS 'COUNT', GENERATION
from CTE
WHERE ID NOT IN (SELECT distinct PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION