-- 코드를 입력하세요
SELECT A.CAR_ID, 
       CASE WHEN B.CAR_ID <> '' THEN "대여중" 
                                ELSE "대여 가능" 
       END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A 
    LEFT OUTER JOIN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE DATE('2022-10-16') BETWEEN DATE(START_DATE) AND DATE(END_DATE) ) AS B ON B.CAR_ID = A.CAR_ID
 GROUP BY A.CAR_ID
 ORDER BY A.CAR_ID DESC
