-- 코드를 입력하세요
SELECT B.PRODUCT_ID, 
       A.PRODUCT_NAME,	
       A.PRICE * SUM(B.AMOUNT) AS 'TOTAL_SALES'
  FROM FOOD_PRODUCT AS A 
    JOIN FOOD_ORDER  AS B ON B.PRODUCT_ID = A.PRODUCT_ID
 WHERE YEAR(B.PRODUCE_DATE) = '2022'
   AND MONTH(B.PRODUCE_DATE) = '05'
 GROUP BY B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, B.PRODUCT_ID ASC