-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT A.FLAVOR, 
             SUM(A.TOTAL_ORDER) + B.TOTAL_ORDER AS SUM_JULY_TOTAL_ORDER
        FROM JULY AS A 
        LEFT OUTER JOIN FIRST_HALF AS B ON B.FLAVOR = A.FLAVOR
       GROUP BY A.FLAVOR, B.TOTAL_ORDER ) AS A 
ORDER BY SUM_JULY_TOTAL_ORDER DESC
LIMIT 3;
 