-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
  FROM MEMBER_PROFILE 
 WHERE MONTH(DATE_OF_BIRTH) = '3'   -- 생일이 3월
   AND GENDER ='W'                  -- 여성 회원
   AND TLNO IS NOT NULL             -- 전화번호 NULL 제외
 ORDER BY MEMBER_ID