SELECT A.MEMBER_NAME, B.REVIEW_TEXT, CONVERT(B.REVIEW_DATE, char) AS REVIEW_DATE
  FROM MEMBER_PROFILE  AS A 
    LEFT OUTER JOIN REST_REVIEW AS B ON B.MEMBER_ID = A.MEMBER_ID
	LEFT OUTER JOIN  (SELECT MEMBER_ID, RANK() OVER(ORDER BY CNT desc) AS CNT
									 FROM (SELECT  MEMBER_ID, COUNT(1) AS CNT
									                      FROM REST_REVIEW
									                      GROUP BY MEMBER_ID
														  ORDER BY COUNT(1)  desc) AS A ) AS C ON C.MEMBER_ID = A.MEMBER_ID

WHERE C.CNT = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT