-- 코드를 작성해주세요
SELECT B.ITEM_ID, A.ITEM_NAME, A.RARITY
  FROM ITEM_INFO AS A 
    LEFT OUTER JOIN ITEM_TREE AS B ON B.ITEM_ID = A.ITEM_ID
    LEFT OUTER JOIN ITEM_INFO AS C ON C.ITEM_ID = B.PARENT_ITEM_ID
 WHERE B.PARENT_ITEM_ID IS NOT NULL    -- 부모 Item_ID가 있는 건
   AND C.RARITY = 'RARE'
 ORDER BY ITEM_ID DESC                 -- ITEM_ID 기준 내림차순