-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
  FROM ANIMAL_INS AS A
    LEFT OUTER JOIN ANIMAL_OUTS AS B ON B.ANIMAL_ID = A.ANIMAL_ID 
                                    AND B.ANIMAL_TYPE = A.ANIMAL_TYPE
 WHERE A.DATETIME > B.DATETIME
 ORDER BY A.DATETIME