-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS 'TOTAL_SALES'
  FROM BOOK AS A 
    LEFT OUTER JOIN BOOK_SALES AS B ON B.BOOK_ID = A.BOOK_ID
 WHERE LEFT(B.SALES_DATE,7) = '2022-01'
 GROUP BY A.CATEGORY
 ORDER BY A.CATEGORY