-- 코드를 입력하세요
SELECT A.BOOK_ID,	B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE,'%Y-%m-%d') AS 'PUBLISHED_DATE'
  FROM BOOK AS A 
    LEFT OUTER JOIN AUTHOR AS B ON B.AUTHOR_ID = A.AUTHOR_ID
 WHERE CATEGORY ='경제'
 ORDER BY PUBLISHED_DATE